backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    slug: "{{slug}}"
    nested:
      depth: 2
    create: true
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
        required: true
      - label: "Descripción"
        name: "description"
        widget: string
      - label: "Autor"
        name: "author"
        widget: "string"
        default: "Datasketch"
      - label: "Imagen"
        name: "image"
        widget: "image"
        allow_multiple: false
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Contenido"
        name: "body"
        widget: "markdown"
